# Generated by Django 5.2.12 on 2026-03-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(default='en-US', max_length=10),
        ),
    ]
