# Generated by Django 5.2.12 on 2026-03-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
